const Question = require('./models/Question');

const qData = [
  // == OPERATING SYSTEM - EASY == 
  { topic: 'Operating System', difficulty: 'easy', text: 'Which of the following is an Operating System?', options: ['Windows', 'Oracle', 'MySQL', 'MongoDB'], correctAnswer: 'Windows', explanation: 'Windows is an operating system while the others are database systems.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'What is the main function of the command interpreter?', options: ['Execute next command', 'Handle files', 'API interface', 'Hardware control'], correctAnswer: 'Execute next command', explanation: 'A command interpreter parses and executes user commands.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'GUI stands for:', options: ['Global User Interface', 'Graphical User Interface', 'Graphic Union Interface', 'Global Union Interface'], correctAnswer: 'Graphical User Interface', explanation: 'GUI allows users to interact with UI using graphical elements.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'Which part of the OS is resident in memory?', options: ['The kernel', 'The shell', 'The desktop', 'The filesystem'], correctAnswer: 'The kernel', explanation: 'The kernel is the core part of the OS loaded closely to memory.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'What is a process?', options: ['A program in execution', 'A stored program', 'A hardware device', 'A network socket'], correctAnswer: 'A program in execution', explanation: 'A process is an active entity executing code.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'Which structure tracks open files?', options: ['Open-file table', 'File assignment table', 'Process table', 'PCB'], correctAnswer: 'Open-file table', explanation: 'The OS tracks all dynamically open files in the open-file table.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'What does booting do?', options: ['Starts the OS from disk to RAM', 'Shuts down the PC', 'Compiles code', 'Scans for viruses'], correctAnswer: 'Starts the OS from disk to RAM', explanation: 'Booting loads the operating system into memory.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'What is the role of a device driver?', options: ['Communicate with specific hardware', 'Manage memory', 'Schedule algorithms', 'Network connection'], correctAnswer: 'Communicate with specific hardware', explanation: 'Device drivers provide software interfaces referencing specific hardware details.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'Where does the BIOS reside?', options: ['ROM', 'RAM', 'Hard Drive', 'Cache'], correctAnswer: 'ROM', explanation: 'BIOS resides in Read-Only Memory to bootstrap the computer.' },
  { topic: 'Operating System', difficulty: 'easy', text: 'What does a page fault mean?', options: ['Page corrupted', 'Page not in main memory', 'Page locked', 'Page not in secondary storage'], correctAnswer: 'Page not in main memory', explanation: 'Occurs when a running process accesses a memory page not loaded in RAM.' },

  // == OPERATING SYSTEM - MEDIUM ==
  { topic: 'Operating System', difficulty: 'medium', text: 'What is a context switch?', options: ['Switching process state', 'Saving state of one process and loading another', 'User to kernel mode', 'Terminating a process'], correctAnswer: 'Saving state of one process and loading another', explanation: 'A context switch swaps out a process to run another context securely.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'Which scheduling algorithm may lead to starvation?', options: ['Round Robin', 'Shortest Job First', 'First Come First Serve', 'Multilevel Queue'], correctAnswer: 'Shortest Job First', explanation: 'SJF can starve larger jobs if small ones keep arriving.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'Semaphore is a:', options: ['Hardware device', 'Integer variable for critical section', 'System call', 'I/O operation'], correctAnswer: 'Integer variable for critical section', explanation: 'Semaphores help solve synchronization problems with locking.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'Thrashing occurs when:', options: ['High page fault rate', 'Minimal swapping', 'Processes finish quickly', 'Low page fault rate'], correctAnswer: 'High page fault rate', explanation: 'When an OS spends more time paging than executing processes.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'Which memory allocation strategy allocates the smallest large-enough block?', options: ['First fit', 'Best fit', 'Worst fit', 'Next fit'], correctAnswer: 'Best fit', explanation: 'Best fit searches entire list to find the smallest suitable gap.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'What is Belady’s anomaly?', options: ['Adding more frames increases page faults', 'Adding more frames decreases page faults', 'No faults occur', 'Deadlock triggers unexpectedly'], correctAnswer: 'Adding more frames increases page faults', explanation: 'In FIFO algorithms, adding memory frames can mathematically increase faults temporarily.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'Spooling stands for:', options: ['Simultaneous Peripheral Operation Online', 'Simple Peripheral Operation Online', 'Simple Process Organized Online', 'Simultaneous Process Operation Online'], correctAnswer: 'Simultaneous Peripheral Operation Online', explanation: 'It is a technique for buffering data for peripherals.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'What is deadlock?', options: ['Infinite loop', 'Two processes waiting on each other indefinitely', 'High memory usage', 'Crashed kernel'], correctAnswer: 'Two processes waiting on each other indefinitely', explanation: 'Occurs when processes hold items while waiting for resources held by others.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'Which is not a condition for deadlock?', options: ['Mutual exclusion', 'Hold and wait', 'Preemption', 'Circular wait'], correctAnswer: 'Preemption', explanation: 'No Preemption is a condition. Preemption resolves deadlocks.' },
  { topic: 'Operating System', difficulty: 'medium', text: 'An interrupt vector contains:', options: ['Memory sizes', 'Addresses of interrupt service routines', 'System PIDs', 'Device states'], correctAnswer: 'Addresses of interrupt service routines', explanation: 'It provides direct pointers to instructions handling hardware interrupts.' },

  // == OPERATING SYSTEM - HARD ==
  { topic: 'Operating System', difficulty: 'hard', text: 'Which algorithm is used to prevent deadlock?', options: ["Banker's Algorithm", "Dijkstra's Algorithm", "Bellman-Ford", 'Kruskal'], correctAnswer: "Banker's Algorithm", explanation: "Banker's Algorithm simulates resource allocation to avoid unsafe states." },
  { topic: 'Operating System', difficulty: 'hard', text: 'In virtual memory, what is dirty bit used for?', options: ['Indicate a page was modified', 'Indicate corrupted memory', 'Indicate read-only', 'Indicate executing page'], correctAnswer: 'Indicate a page was modified', explanation: 'The dirty bit signals if a page must be written back to disk.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'TLB stands for:', options: ['Translation Lookaside Buffer', 'Transfer Local Buffer', 'Thread Language Block', 'Time Latency Buffer'], correctAnswer: 'Translation Lookaside Buffer', explanation: 'TLB is a cache that memory management hardware uses for virtual address translation.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'How does a monitor construct differ from a semaphore?', options: ['It uses integer values only', 'It guarantees mutual exclusion naturally', 'It requires spinlocks', 'It operates at hardware level'], correctAnswer: 'It guarantees mutual exclusion naturally', explanation: 'Monitors are high-level abstractions where only one process is active at a time inside.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'What is an inverted page table?', options: ['Table indexed by physical frame', 'Table indexed by virtual frame', 'Table stored on disk only', 'Table stored in registers'], correctAnswer: 'Table indexed by physical frame', explanation: 'It maps physical memory to logical pages, reducing overall memory consumed by tables.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'What is a spinlock?', options: ['A lock using busy waiting', 'A lock using sleeping', 'A lock for file system', 'A network lock'], correctAnswer: 'A lock using busy waiting', explanation: 'A process repeatedly checks if the lock is available (busy waiting).' },
  { topic: 'Operating System', difficulty: 'hard', text: 'What is priority inversion?', options: ['High priority waits on low priority holding a lock', 'Low priority waits on high priority', 'Priority values are inverted', 'All priorities reset'], correctAnswer: 'High priority waits on low priority holding a lock', explanation: 'A low priority task blocks a high priority one because it locked a shared resource.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'Which RAID level provides mirroring?', options: ['RAID 0', 'RAID 1', 'RAID 5', 'RAID 6'], correctAnswer: 'RAID 1', explanation: 'RAID 1 mirrors identically down to the block level.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'A zombie process is:', options: ['Completed but still has an entry in process table', 'Running infinitely', 'Attacking the OS', 'Consuming network bandwidth'], correctAnswer: 'Completed but still has an entry in process table', explanation: 'Its completion status hasn’t been read by its parent yet.' },
  { topic: 'Operating System', difficulty: 'hard', text: 'In Linux, what system call is used to create a new process?', options: ['exec()', 'fork()', 'spawn()', 'clone()'], correctAnswer: 'fork()', explanation: 'fork() creates a duplicate process representing the child.' },

  // == COMPUTER NETWORK - EASY ==
  { topic: 'Computer Network', difficulty: 'easy', text: 'What does IP stand for?', options: ['Internet Protocol', 'Intranet Protocol', 'Internal Process', 'Internet Provider'], correctAnswer: 'Internet Protocol', explanation: 'IP handles routing across networks.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'What is the default port number for HTTP?', options: ['21', '22', '80', '443'], correctAnswer: '80', explanation: 'Port 80 is historically used for insecure HTTP traffic.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'What is the full form of DNS?', options: ['Domain Name Server', 'Data Name Service', 'Domain Name System', 'Dynamic Naming System'], correctAnswer: 'Domain Name System', explanation: 'DNS translates human readable names to IP addresses.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'What is the primary function of a Router?', options: ['Connect networks together', 'Amplify signals', 'Convert AC to DC', 'Read DNS files'], correctAnswer: 'Connect networks together', explanation: 'Routers operate at the Network layer to forward packets across different networks.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'Which topology uses a central hub?', options: ['Ring', 'Star', 'Bus', 'Mesh'], correctAnswer: 'Star', explanation: 'In a Star topology, all nodes connect to a central Hub or Switch.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'What command verifies remote host reachability?', options: ['Ping', 'Ipconfig', 'Traceroute', 'Netstat'], correctAnswer: 'Ping', explanation: 'Ping uses ICMP echo requests to measure reachability and round trip time.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'Which refers to the layout of a network?', options: ['Protocol', 'Topology', 'Architecture', 'Syntax'], correctAnswer: 'Topology', explanation: 'Topology refers to the geometric arrangement of devices.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'URL stands for?', options: ['Uniform Resource Locator', 'Universal Routing Link', 'Unified Resource List', 'Uniform Routing Layer'], correctAnswer: 'Uniform Resource Locator', explanation: 'URL specifies the location of a web resource.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'What protocol secures websites?', options: ['HTTP', 'FTP', 'HTTPS', 'SMTP'], correctAnswer: 'HTTPS', explanation: 'HTTPS encrypts data transfers with SSL/TLS.' },
  { topic: 'Computer Network', difficulty: 'easy', text: 'Bluetooth targets which type of network area?', options: ['PAN', 'LAN', 'WAN', 'MAN'], correctAnswer: 'PAN', explanation: 'Personal Area Networks cover small distances like Bluetooth.' },

  // == COMPUTER NETWORK - MEDIUM ==
  { topic: 'Computer Network', difficulty: 'medium', text: 'Which protocol is used to find MAC from an IP address?', options: ['RARP', 'ARP', 'ICMP', 'IGMP'], correctAnswer: 'ARP', explanation: 'Address Resolution Protocol maps IP addresses to physical MAC layers.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'In IPv4, an IP address is how many bits?', options: ['16 bits', '32 bits', '64 bits', '128 bits'], correctAnswer: '32 bits', explanation: 'IPv4 consists of four 8-bit octets.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'Which protocol provides reliable data transfer?', options: ['UDP', 'TCP', 'IP', 'ICMP'], correctAnswer: 'TCP', explanation: 'TCP guarantees orderly and reliable data sequence.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'What is the subnet mask for a default Class C IP address?', options: ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'], correctAnswer: '255.255.255.0', explanation: 'Class C uses 24 bits for the network part.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'Device operating at OSI Network layer?', options: ['Hub', 'Switch', 'Router', 'Repeater'], correctAnswer: 'Router', explanation: 'Routers handle logical IP addressing via Network layer.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'What does NAT stand for?', options: ['Network Address Translation', 'Node Allocation Table', 'New Access Transfer', 'Network Area Topology'], correctAnswer: 'Network Address Translation', explanation: 'NAT maps private local addresses to public global ones.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'Which layer is not present in the TCP/IP model?', options: ['Application', 'Presentation', 'Transport', 'Internet'], correctAnswer: 'Presentation', explanation: 'TCP/IP combines OSI OSI Application, Presentation, Session layers into just Application.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'Size of a MAC address?', options: ['32 bits', '48 bits', '64 bits', '128 bits'], correctAnswer: '48 bits', explanation: 'MAC addresses are physical 48-bit unique identifiers.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'Which DNS record points a domain to an IP?', options: ['MX', 'CNAME', 'A', 'TXT'], correctAnswer: 'A', explanation: 'An A record links domain names explicitly to IPv4 addresses.' },
  { topic: 'Computer Network', difficulty: 'medium', text: 'Protocol used to send email?', options: ['POP3', 'IMAP', 'SMTP', 'FTP'], correctAnswer: 'SMTP', explanation: 'Simple Mail Transfer Protocol transmits outbound email messages.' },

  // == COMPUTER NETWORK - HARD ==
  { topic: 'Computer Network', difficulty: 'hard', text: 'Which field in IPv4 prevents packet loops?', options: ['TTL', 'Checksum', 'Fragment Offset', 'Protocol'], correctAnswer: 'TTL', explanation: 'Time to Live drops down on every hop, stopping loops if it reaches 0.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'What is BGP classification?', options: ['IGP', 'Distance Vector', 'EGP', 'Link State'], correctAnswer: 'EGP', explanation: 'BGP is an Exterior Gateway Protocol routing between autonomous systems.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'In OSI, reliable process-to-process delivery is handled by:', options: ['Network Layer', 'Data Link Layer', 'Transport Layer', 'Application Layer'], correctAnswer: 'Transport Layer', explanation: 'The transport layer performs port-level segmentation and reliability functions.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'An IP attack that tricks ARP caches is called:', options: ['ARP Spoofing', 'IP Spoofing', 'DDoS', 'Phishing'], correctAnswer: 'ARP Spoofing', explanation: 'ARP Spoofing maps an attackers MAC to a legitimate IP dynamically.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'Which algorithm is typically used in Link State Routing?', options: ['Bellman-Ford', 'Dijkstra', 'Floyd-Warshall', 'Kruskal'], correctAnswer: 'Dijkstra', explanation: 'OSPF and Link State protocols utilize shortest path first.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'How large is an IPv6 address?', options: ['32 bits', '64 bits', '128 bits', '256 bits'], correctAnswer: '128 bits', explanation: 'IPv6 uses 128-bit hex string allocations.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'TCP 3-way handshake sequence is:', options: ['SYN, SYN-ACK, ACK', 'ACK, SYN, FIN', 'SYN, ACK, PSH', 'SYN, ACK-SYN, ACK'], correctAnswer: 'SYN, SYN-ACK, ACK', explanation: 'This sequence synchronizes logic states bidirectionally.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'In sliding window protocol, what improves efficiency over Stop-and-Wait?', options: ['Piggybacking', 'Sending multiple frames before ACK', 'Compression', 'Window scaling purely'], correctAnswer: 'Sending multiple frames before ACK', explanation: 'You pipe data blocks allowing continuous flight.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'VLAN membership operates essentially at which layer?', options: ['Layer 1', 'Layer 2', 'Layer 3', 'Layer 4'], correctAnswer: 'Layer 2', explanation: 'Virtual LANs tag switch frames at the data link layer visually separating broadcast.' },
  { topic: 'Computer Network', difficulty: 'hard', text: 'CSMA/CD is used for:', options: ['Token Ring', 'Ethernet', 'Wireless LAN', 'FDDI'], correctAnswer: 'Ethernet', explanation: 'Carrier Sense Multiple Access with Collision Detection arbitrates shared Ethernet access.' },

  // == OPERATIONS RESEARCH - EASY ==
  { topic: 'Operations Research', difficulty: 'easy', text: 'What is the goal of Operations Research?', options: ['Optimize decision making', 'Maximize hardware usage', 'Develop algorithms', 'Write faster code'], correctAnswer: 'Optimize decision making', explanation: 'OR applies math models for analytical decision improvement.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'What is a feasible region?', options: ['Goal sum zero', 'Set of points satisfying constraints', 'The maximum point', 'An algorithm phase'], correctAnswer: 'Set of points satisfying constraints', explanation: 'Feasible regions contain all mathematically allowed solutions.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'Which solves LP problems?', options: ['Simplex Method', 'Bubble Sort', 'Binary Search', 'A*'], correctAnswer: 'Simplex Method', explanation: 'Simplex systematically explores feasible vertices iteratively.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'Transportation problems try to minimize:', options: ['Total revenue', 'Transportation cost', 'Total supply', 'Delivery time exclusively'], correctAnswer: 'Transportation cost', explanation: 'Usually minimizing the mathematical shipment cost graph.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'PERT stands for?', options: ['Program Evaluation and Review Technique', 'Project Execution Technique', 'Process Evaluation Technique', 'Program Event Routing Table'], correctAnswer: 'Program Evaluation and Review Technique', explanation: 'It is a statistical tool used in project management.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'Which model deals with customer queues?', options: ['Inventory Model', 'Queuing Model', 'Network Model', 'Simulation Model'], correctAnswer: 'Queuing Model', explanation: 'Queuing theory solves waiting lines analytically.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'In game theory, zero-sum implies:', options: ['Nobody wins', 'Sum of payoffs is zero', 'No optimal strategy', 'Draw match'], correctAnswer: 'Sum of payoffs is zero', explanation: 'Gains for one participant exactly match losses for the other.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'Critical path dictates:', options: ['Shortest network path', 'Longest project execution path', 'Cheapest path', 'Path with slack'], correctAnswer: 'Longest project execution path', explanation: 'It represents the bottleneck activities defining total completion time.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'What purpose does graphical method serve?', options: ['Solve 2-variable LP models', 'Draw charts', 'Solve network flows', 'Identify critical paths'], correctAnswer: 'Solve 2-variable LP models', explanation: 'Humans graphically plot overlapping inequality boundaries in 2D space.' },
  { topic: 'Operations Research', difficulty: 'easy', text: 'Which is an inventory model?', options: ['EOQ', 'CPM', 'Simplex', 'VAM'], correctAnswer: 'EOQ', explanation: 'Economic Order Quantity resolves ideal stock purchases.' },

  // == OPERATIONS RESEARCH - MEDIUM ==
  { topic: 'Operations Research', difficulty: 'medium', text: 'First step in transportation problem?', options: ['Find IBFS', 'Optimize using MODI', 'Draw graph', 'Simplex'], correctAnswer: 'Find IBFS', explanation: 'Initial Basic Feasible Solution is required before checking mathematical optimality.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'What is a slack variable?', options: ['Represents unused resources', 'Represents minimum bound', 'Artificial identifier', 'Cost element'], correctAnswer: 'Represents unused resources', explanation: 'Slack turns inequalities (<=) into equalities.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'Which algorithm solves assignment problems?', options: ['Hungarian Method', 'Simplex', 'MODI', 'Vogel'], correctAnswer: 'Hungarian Method', explanation: 'Hungarian safely structures one-to-one matrix matching assignments.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'What does CPM stand for?', options: ['Critical Path Method', 'Continuous Path Model', 'Critical Project Method', 'Control Point Metric'], correctAnswer: 'Critical Path Method', explanation: 'CPM strictly computes deterministic network pathways.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'If primal constraint is equality, what is the dual variable?', options: ['Unrestricted in sign', 'Zero', 'Negative', 'Positive'], correctAnswer: 'Unrestricted in sign', explanation: 'It allows unbounded projection representing exact threshold matching.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'Vogel Approximation Method (VAM) determines:', options: ['Optimal solution', 'IBFS', 'Simplex pivot', 'Critical Path'], correctAnswer: 'IBFS', explanation: 'VAM calculates grid penalties to find strong Initial Feasible approximations.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'In queuing theory, M/M/1 specifies:', options: ['Poisson arrival, Exponential service, 1 server', 'Mathematical Model 1', 'Mean metrics 1', 'Deterministic'], correctAnswer: 'Poisson arrival, Exponential service, 1 server', explanation: 'Kendall notation categorizing distinct queuing dynamics.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'Dummy activities in networks:', options: ['Have no duration', 'Help identify critical path', 'Are optional decorations', 'Cost extra'], correctAnswer: 'Have no duration', explanation: 'They solely clarify topological precedence graphs.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'When is a transportation problem unbalanced?', options: ['Supply != Demand', 'Many columns', 'Empty matrices', 'Infinite cost'], correctAnswer: 'Supply != Demand', explanation: 'Fictitious dummy nodes balance unequal supply and demand constraints.' },
  { topic: 'Operations Research', difficulty: 'medium', text: 'What does a saddle point represent?', options: ['Optimal game theory solution', 'Deadlock', 'Infeasible constraint', 'Alternate optimum'], correctAnswer: 'Optimal game theory solution', explanation: 'It is the Nash equilibrium state where neither player benefits from shifting.' },

  // == OPERATIONS RESEARCH - HARD ==
  { topic: 'Operations Research', difficulty: 'hard', text: 'Dual of a dual LP problem is:', options: ['Primal problem', 'Dual', 'Infeasible', 'Unbounded'], correctAnswer: 'Primal problem', explanation: 'The mathematical transpose reflection resolves symmetrically.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'What does degeneracy in transportation problems mean?', options: ['Basic cells < m+n-1', 'Basic cells = m+n-1', 'Negative cost', 'Loops form'], correctAnswer: 'Basic cells < m+n-1', explanation: 'Degeneracy requires epsilon adjustments because assigned routes are too few.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'In Integer Programming, which method isolates branch planes?', options: ['Branch and Bound', 'MODI', 'Simplex array', 'Northwest Corner'], correctAnswer: 'Branch and Bound', explanation: 'It slices optimal linear answers sequentially testing exact integers bounds.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'Little’s Law formula is:', options: ['L = λW', 'L = λ/W', 'W = L * λ^2', 'L = W/λ'], correctAnswer: 'L = λW', explanation: 'Relates average queue length directly with wait time and arrival λ.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'Big-M method achieves:', options: ['Penalty variables solving >= constraints', 'Faster permutations', 'Matrix size increases', 'Random constraints'], correctAnswer: 'Penalty variables solving >= constraints', explanation: 'Assigns massive artificial costs mathematically pushing solver towards feasibility.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'In dynamic programming, what is the principle of optimality?', options: ['Any subpolicy of an optimal policy is itself optimal', 'Simplex bounds', 'Highest node first', 'Network loops'], correctAnswer: 'Any subpolicy of an optimal policy is itself optimal', explanation: 'Bellman’s core equation relies on modular fractional optimizations.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'Using the MODI method, optimal route sets are tested via:', options: ['u_i + v_j criteria on empty cells', 'Slack reductions', 'Dummy row additions', 'Graphical pivots'], correctAnswer: 'u_i + v_j criteria on empty cells', explanation: 'It evaluates reduced opportunity costs mapping unassigned grid potentials.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'What distribution describes service times in typical Queuing models?', options: ['Exponential', 'Normal', 'Uniform', 'Binomial'], correctAnswer: 'Exponential', explanation: 'It accurately models memoryless variable interaction speeds.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'What happens if a basic variable coefficient evaluates to 0 on simplex Z-row?', options: ['Alternative optima exists', 'Primal infeasible', 'Degeneracy bound', 'Matrix undefined'], correctAnswer: 'Alternative optima exists', explanation: 'Sliding variables enter basis without penalty altering profit/loss.' },
  { topic: 'Operations Research', difficulty: 'hard', text: 'What does sensitivity analysis do in Linear Programming?', options: ['Studies effect of changing parameters on optimal solutions', 'Calculates exact simplex ratios', 'Converts to dual instantly', 'Deletes dummy nodes'], correctAnswer: 'Studies effect of changing parameters on optimal solutions', explanation: 'Post-optimality review on boundary shifts preventing re-execution.' }
];

const seedQuestions = async () => {
  try {
    const count = await Question.countDocuments();
    if (count === 0) {
      await Question.insertMany(qData);
      console.log('Seeded database with exactly 90 unique questions.');
    } else {
      await Question.deleteMany({});
      await Question.insertMany(qData);
      console.log('Wiped and reseeded database perfectly to 90 distinct complex questions.');
    }
  } catch (error) {
    console.error('Error seeding questions:', error);
  }
};

module.exports = { seedQuestions };
